language: rust
matrix:
  include:
    - os: linux
      rust: nightly
      dist: trusty
    - os: linux
      rust: stable
      dist: trusty
    - os: osx
      rust: nightly
    - os: osx
      rust: stable
cache: cargo
